"""Добавили таблицу связки

Revision ID: 000006e5125b
Revises: dde1ee14d67e
Create Date: 2025-02-04 22:35:39.309987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000006e5125b'
down_revision = 'dde1ee14d67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solved tasks',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('count_tasks',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('count_correct_tasks',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('count_correct_tasks',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('count_tasks',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('solved tasks')
    # ### end Alembic commands ###
