"""добавление новых полей

Revision ID: 9955124abed3
Revises: 000006e5125b
Create Date: 2025-03-05 23:34:59.241751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9955124abed3'
down_revision = '000006e5125b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solved tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.Integer(), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_solution', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('link_solution')

    with op.batch_alter_table('solved tasks', schema=None) as batch_op:
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
