"""added count_tasks

Revision ID: dde1ee14d67e
Revises: bc6567024948
Create Date: 2025-01-05 15:41:27.221125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde1ee14d67e'
down_revision = 'bc6567024948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_tasks', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('count_correct_tasks', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('count_correct_tasks')
        batch_op.drop_column('count_tasks')

    # ### end Alembic commands ###
